environment:
  PYTHONPATH: lib
  matrix:
    - PYTHON: "C:\\Python27"
install:
  - "%PYTHON%\\python.exe -m pip install pipenv"
  - "%PYTHON%\\python.exe -m pipenv install -d --system --deploy"
  - "%PYTHON%\\python.exe -m pip install -r Documentation/requirements.txt"
build_script:
  - "%PYTHON%\\python.exe build.py"
  - "Documentation/make.bat html"
after_build:
  - "7z a -tzip -xr!.* -xr0!build build\\NukeBatchRender-%APPVEYOR_REPO_TAG_NAME%-win.zip"
artifacts:
  - path: build\NukeBatchRender-*.zip
    name: Prebuild package
before_deploy:
  - ps: >-
      & $env:PYTHON\\python.exe Documentation/get_changelog.py $env:APPVEYOR_REPO_TAG_NAME build/release_note.md;
      ${env:APPVEYOR_RELEASE_DESCRIPTION} = (Get-Content -Encoding utf8 build/release_note.md) -join "`n";
deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_RELEASE_DESCRIPTION)
  provider: GitHub
  auth_token:
    secure: nsLSikshpVvfyMmNivRtOSZT3xmqO5iD6nOkoXipGnT33lU19R89mfpDXZjAuyjr
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
